### PR TITLE
fixed $RBENV_BUILD directory name

### PR DESCRIPTION
**Pull request by annarankin**

### CODE REVIEW

**Comment by h4w5** [comment]
Awesome catch! Thanks!

**Comment by h4w5** [comment]
@annarankin

Ah, just tested this!

So the correction is real, but the change should be made in a different place. I'm going to go ahead and make the change, and will mention that diff below, so you can see how it works.

Essentially, think of the "builds" as the output of a build process. You should edit the "scripts" instead, and then rerun the process to create the build.

**Comment by h4w5** [comment]
Here is the change: #0a238d1

I made the change in `scripts/rbenv_install.sh`, and then rebuilt the script:

```
$ rake installer:build
```

Thanks again!

**Comment by h4w5** [comment]
Closes #86.

**Comment by annarankin** [comment]
Whoops! I see now... Thanks @h4w5!

**Pull request merged**
